In [2]:
import numpy as np 

In [ ]:
# numpy 
# linear algebra,arith,fourier transforms,matrix operations,stat
# it works on arrays

In [20]:
a=np.array(12+7j)  

In [21]:
a


array(12.+7.j)

In [24]:
np.array('python class is delayed')# error

array('python class is delayed', dtype='<U23')

In [29]:
np.array(12,dtype=np.complex128)

array(12.+0.j)

In [3]:
np.array([1,2,3,4,5.4,6],dtype=np.float64) #1D array,row matrix

array([1. , 2. , 3. , 4. , 5.4, 6. ])

In [39]:
np.array([[1,2],[3,4],[7,8]],dtype=np.float64) 

array([[1., 2.],
       [3., 4.],
       [7., 8.]])

In [40]:
np.array((1,2,3,4,5,6))

array([1, 2, 3, 4, 5, 6])

In [41]:
np.array(((1,2),(4,5),(7,8)))

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
np.array({1:234,78:67})

array({1: 234, 78: 67}, dtype=object)

In [47]:
np.array({1,2,3,4,4,5,5,5,6,6,6,6})

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [53]:
np.array(True,dtype=np.float64)

array(1.)

In [51]:
np.array(False,dtype=np.float64)

array(0.)

In [54]:
# automatic methods

In [69]:
np.arange(-0,11,2)# imp

array([ 0,  2,  4,  6,  8, 10])

In [76]:
np.arange(-11,-1,2)

array([-11,  -9,  -7,  -5,  -3])

In [74]:
np.arange(-1,-11,-1)

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [82]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [85]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
np.ones(3)

array([1., 1., 1.])

In [89]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.random.randint(2.1,10.0,10)
    

array([6, 5, 3, 6, 7, 5, 8, 5, 6, 8])

In [142]:
np.random.randn(2,3,3)

array([[[ 0.06301384,  1.30814864,  0.04011979],
        [ 0.19918236,  0.08921885,  0.1853086 ],
        [-0.37406991, -0.7827739 ,  0.40452206]],

       [[ 0.51798291, -0.66242099,  0.87898291],
        [ 1.05642116,  0.98508405, -0.75578431],
        [-1.66636268,  2.51632513, -0.69285073]]])

In [143]:
np.random.rand(2,3,2)# 0 and 1

array([[[0.94760261, 0.67808728],
        [0.77013339, 0.22843601],
        [0.49603528, 0.90403691]],

       [[0.22512841, 0.8943698 ],
        [0.10814697, 0.3351795 ],
        [0.80166232, 0.70792434]]])

In [144]:
# attributes of array

In [145]:
abc=np.arange(0,15)
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
qwe=np.random.randn(15)
qwe

array([ 1.26375458,  0.23662062,  1.34069129,  0.40803875,  0.88481462,
        0.19947219, -1.4710648 , -0.05053487,  1.24980041,  1.09946526,
        0.58077177, -0.68572969, -0.61309025, -0.40700909, -1.10640424])

In [148]:
abc.dtype

dtype('int32')

In [149]:
qwe.dtype

dtype('float64')

In [150]:
abc.size

15

In [151]:
abc.itemsize 4 bytes of memory

4

In [8]:
qwe.itemsize

8

In [153]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [155]:
abc.argmax()

14

In [156]:
abc.argmin()

0

In [157]:
max(abc)

14

In [158]:
min(abc)

0

In [159]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [161]:
abc.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105], dtype=int32)

In [162]:
qwe.cumprod()

array([-8.51696767e-01,  2.23711389e-02,  5.01152145e-03,  3.02296222e-03,
        7.31553885e-03,  1.44235228e-03,  1.14477695e-03,  3.15197856e-04,
        2.31789789e-04, -2.22348685e-04,  1.31665379e-04, -9.41430288e-05,
        2.56029025e-04, -3.82447618e-04, -1.92380644e-04])

In [164]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [163]:
abc.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [165]:
qwe

array([-0.85169677, -0.02626655,  0.22401727,  0.60320249,  2.41999017,
        0.19716282,  0.79368748,  0.27533561,  0.7353787 , -0.95926868,
       -0.59215722, -0.71501734, -2.71957497, -1.49376664,  0.50302482])

In [10]:
qwe.argmax()

2

In [168]:
abc.mean()

7.0

In [172]:
qwe.mean()

-0.1070632544271281

In [173]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [174]:
np.sqrt(abc)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [178]:
np.square(abc)


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [179]:
np.cos(abc)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722])

In [180]:
np.sin(abc)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [181]:
abc=[1,2,3,4,5,np.nan]

In [182]:
abc

[1, 2, 3, 4, 5, nan]

In [186]:
a=np.array(abc)
a

array([ 1.,  2.,  3.,  4.,  5., nan])

In [189]:
np.isnan(abc)

array([False, False, False, False, False,  True])

In [196]:
q=np.arange(1,10)
a=np.arange(11,20)
print(q)
print(a)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [197]:
q+a

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [199]:
q-a

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [200]:
q*a

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [201]:
q/a

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [202]:
q//a

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [203]:
q%a

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [208]:
(q+a)/q*a-q**q

array([ 1.31000000e+02,  8.00000000e+01,  4.23333333e+01, -1.93000000e+02,
       -3.06500000e+03, -4.65973333e+04, -8.23484714e+05, -1.67771575e+07,
       -3.87420430e+08])

In [209]:
abc=[[1,2],[4,5],[8,9]]

In [212]:
a=np.array(abc)
a

array([[1, 2],
       [4, 5],
       [8, 9]])

In [218]:
a%2

array([[1, 0],
       [0, 1],
       [0, 1]], dtype=int32)

In [219]:
a+a

array([[ 2,  4],
       [ 8, 10],
       [16, 18]])

In [220]:
abc

[[1, 2], [4, 5], [8, 9]]

In [221]:
a=np.arange(11,20)

In [222]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [229]:
a[a>=15]

array([15, 16, 17, 18, 19])

In [230]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [233]:
a[(a==15)  |  (a>15)]

array([15, 16, 17, 18, 19])

In [234]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [235]:
a[a!=15]

array([11, 12, 13, 14, 16, 17, 18, 19])

In [237]:
a[a>=15]

array([15, 16, 17, 18, 19])

In [238]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [242]:
a[0:5]=100

In [243]:
a

array([100, 100, 100, 100, 100,  16,  17,  18,  19])

In [245]:
a[0:6:2]=1020

In [246]:
a

array([1020,  100, 1020,  100, 1020,   16,   17,   18,   19])

In [17]:
abc=np.random.randn(3,2,3)

In [18]:
abc

array([[[ 0.49589628,  1.9636673 , -0.6643898 ],
        [ 2.96052311,  1.70403282,  0.66763568]],

       [[-0.03381391, -0.38343821, -2.23400633],
        [ 1.48350498,  2.04994828,  0.47156305]],

       [[-0.20152288, -1.49895012, -1.6986519 ],
        [ 0.15087655, -0.27308071,  0.6224541 ]]])

In [28]:
abc[0:3,1:2]

array([[[ 2.96052311,  1.70403282,  0.66763568]],

       [[ 1.48350498,  2.04994828,  0.47156305]],

       [[ 0.15087655, -0.27308071,  0.6224541 ]]])

In [24]:
for data in abc[:,-2:]:
    print(data)

[[ 0.49589628  1.9636673  -0.6643898 ]
 [ 2.96052311  1.70403282  0.66763568]]
[[-0.03381391 -0.38343821 -2.23400633]
 [ 1.48350498  2.04994828  0.47156305]]
[[-0.20152288 -1.49895012 -1.6986519 ]
 [ 0.15087655 -0.27308071  0.6224541 ]]


In [283]:
for data in abc[:,-2:]:
    print(round(data[1]*2,2))

-3.88
-1.69
-2.62


In [284]:
abc

array([[ 0.22871363,  0.31604567, -1.9400686 ],
       [-1.36688085, -1.19943508, -0.84637025],
       [ 0.9474724 ,  2.15758686, -1.31179508]])

In [285]:
type(abc)

numpy.ndarray

In [286]:
abc.ndim

2

In [288]:
abc

array([[ 0.22871363,  0.31604567, -1.9400686 ],
       [-1.36688085, -1.19943508, -0.84637025],
       [ 0.9474724 ,  2.15758686, -1.31179508]])

In [291]:
plm=np.random.randn(4,5)

In [292]:
plm

array([[-1.30274028, -0.05660112, -0.54821776,  0.71498508,  1.92322914],
       [ 2.11171132, -0.58909227, -0.37029224,  0.93102356,  0.22617192],
       [-2.69330403, -0.5728828 ,  0.02406037,  1.16505921,  0.22974927],
       [-0.56429725, -0.68098219, -0.33129666, -0.53561677, -1.01583359]])

In [293]:
plm.std()

1.0744443932358005

In [303]:
abc=np.array([1,2,3,4])
plm=np.array([8,9,2,3])
             

In [304]:
np.hstack((abc,plm))

array([1, 2, 3, 4, 8, 9, 2, 3])

In [305]:
np.vstack((abc,plm))

array([[1, 2, 3, 4],
       [8, 9, 2, 3]])

In [306]:
np.dstack((abc,plm)) #depth stack

array([[[1, 8],
        [2, 9],
        [3, 2],
        [4, 3]]])

In [307]:
abc

array([1, 2, 3, 4])

In [315]:
np.stack((abc,plm),axis=0)#axis=0, arranging the data along x axis

array([[1, 2, 3, 4],
       [8, 9, 2, 3]])

In [316]:
np.stack((abc,plm),axis=1)# axis=1,arranging the data along y axis

array([[1, 8],
       [2, 9],
       [3, 2],
       [4, 3]])

array([1, 2, 3, 4])

In [319]:
plm

array([8, 9, 2, 3])

In [320]:
plm=np.random.randn(4,5)

In [321]:
plm

array([[ 2.08805693, -0.18732899,  0.01792588, -0.92205167, -0.40646761],
       [ 0.79666239,  0.10669962, -0.93895604, -0.87373695, -0.13219409],
       [ 0.70553037,  0.00335381,  1.18782837, -0.61187093,  0.74016518],
       [ 0.66891317,  0.04838002, -0.54187811, -1.29193668,  0.71163684]])

In [322]:
plm.T

array([[ 2.08805693,  0.79666239,  0.70553037,  0.66891317],
       [-0.18732899,  0.10669962,  0.00335381,  0.04838002],
       [ 0.01792588, -0.93895604,  1.18782837, -0.54187811],
       [-0.92205167, -0.87373695, -0.61187093, -1.29193668],
       [-0.40646761, -0.13219409,  0.74016518,  0.71163684]])

In [331]:
abc=np.arange(1,10)

In [332]:
abc

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [333]:
np.split(abc,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [38]:
plm

array([[-0.85890314,  1.30642594,  1.27854797,  1.34916035],
       [ 0.21363328, -1.37939608,  1.93476795, -0.58810957],
       [ 0.22663963, -0.42982798,  0.60838928,  0.164744  ],
       [-1.29819359,  0.42710579, -0.05562402, -1.92853712]])

In [37]:
np.vsplit(plm,2)

[array([[-0.85890314,  1.30642594,  1.27854797,  1.34916035],
        [ 0.21363328, -1.37939608,  1.93476795, -0.58810957]]),
 array([[ 0.22663963, -0.42982798,  0.60838928,  0.164744  ],
        [-1.29819359,  0.42710579, -0.05562402, -1.92853712]])]

In [32]:
plm=np.random.randn(4,4)

In [33]:
plm

array([[-0.85890314,  1.30642594,  1.27854797,  1.34916035],
       [ 0.21363328, -1.37939608,  1.93476795, -0.58810957],
       [ 0.22663963, -0.42982798,  0.60838928,  0.164744  ],
       [-1.29819359,  0.42710579, -0.05562402, -1.92853712]])

In [35]:
np.hsplit(plm,2)

[array([[-0.85890314,  1.30642594],
        [ 0.21363328, -1.37939608],
        [ 0.22663963, -0.42982798],
        [-1.29819359,  0.42710579]]),
 array([[ 1.27854797,  1.34916035],
        [ 1.93476795, -0.58810957],
        [ 0.60838928,  0.164744  ],
        [-0.05562402, -1.92853712]])]

In [1]:
import numpy as np

np.random.rand(1.0,20.00)

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
a=np.arange(1,-1)

a

array([], dtype=int32)

In [3]:
a=np.arange(5j,0,2)

a

array([], dtype=complex128)

In [4]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [5]:
a=np.random.randint(1,5,12)

a

array([1, 3, 2, 3, 2, 1, 4, 2, 4, 3, 1, 4])